const colors = {
  light: {
    text: "#0D0D0D",
    tint: "#1A6DFF",
    background: "#FFFFFF",
    foreground: "#0D0D0D",
    card: "#F2F2F7",
    cardForeground: "#0D0D0D",
    primary: "#1A6DFF",
    primaryForeground: "#FFFFFF",
    secondary: "#F2F2F7",
    secondaryForeground: "#3C3C43",
    muted: "#F2F2F7",
    mutedForeground: "#8E8E93",
    accent: "#E8F0FF",
    accentForeground: "#1A6DFF",
    destructive: "#FF3B30",
    destructiveForeground: "#FFFFFF",
    border: "#E5E5EA",
    input: "#E5E5EA",
    online: "#34C759",
    blueTick: "#1A6DFF",
    blackTick: "#1C1C1E",
    messageBubble: "#1A6DFF",
    messageBubbleText: "#FFFFFF",
    messageOther: "#F2F2F7",
    messageOtherText: "#0D0D0D",
  },
  dark: {
    text: "#FFFFFF",
    tint: "#4D8FFF",
    background: "#000000",
    foreground: "#FFFFFF",
    card: "#1C1C1E",
    cardForeground: "#FFFFFF",
    primary: "#4D8FFF",
    primaryForeground: "#FFFFFF",
    secondary: "#2C2C2E",
    secondaryForeground: "#EBEBF5",
    muted: "#2C2C2E",
    mutedForeground: "#8E8E93",
    accent: "#1A3366",
    accentForeground: "#4D8FFF",
    destructive: "#FF453A",
    destructiveForeground: "#FFFFFF",
    border: "#38383A",
    input: "#38383A",
    online: "#30D158",
    blueTick: "#4D8FFF",
    blackTick: "#EBEBF5",
    messageBubble: "#1A6DFF",
    messageBubbleText: "#FFFFFF",
    messageOther: "#2C2C2E",
    messageOtherText: "#FFFFFF",
  },
  radius: 12,
};

export default colors;
